### ISSUE TITLE
Export scripts broken on windows

### ISSUE THREAD

**Issue by kaeltara** [gc-net/gaia#120]
## Expected behaviour

The `exportProject` script should be able to successfully deduce whether a selected project is using the *default* or *classic* versions of IM, and export to either `/pubic/deployments/` or `src/Deployments/` accordingly.

## Current behaviour

1. File separators in paths are not interpreted in accordance with the target platform:
Paths resolve to i.e: `infinitymint-beta/src\/Deployments\/...`
2. No files are being written to the export location

**Comment by llydia-eth** [comment]
Fixed :)
